---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_distribution == "Amazon" or ansible_distribution == "Amazon Linux"

  - name: install apache package
    yum: 
      name: httpd
      state: latest
    when: ansible_distribution == "Amazon" or ansible_distribution == "Amazon Linux"

  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "Amazon" or ansible_distribution == "Amazon Linux"
