---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    yum:
      name: '*'
      state: latest
      update_cache: yes

  - name: install apache package
    yum: 
      name: httpd
      state: absent

  - name: add php support for apache
    yum:
      name: php
      state: absent
