---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Amazon" or ansible_distribution == "Amazon Linux"


- hosts: all
  become: true
  roles: 
    - base

- hosts: workstation
  become: true
  roles:
    - workstation

- hosts: web_servers
  become: true
  roles: 
    - web_servers
