---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Amazon" or ansible_distribution == "Amazon Linux"


- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key: 
      user: simone
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCPRFcUtTKM8Zn7oeqDdlm8pNsym/fdUenqXnCDhwwNn3zhAjFtToziwU3M8trzLW5TgZUPOBkh980digAM44nA6MFPja9Zcbtp6M/8/t9Lxr4b5Os80zGpGYgyqGR1LlahD/1AFNW7YJ4sfEUmbfFGrVHkvjEJF5lAYVChDyAutP451WFSo6yocYyN39pxdjbcyG9Y+gWyKEJK2VILj9pMbcw/u22ouqcM2GPUuDT/QAVWuH3ll4XmVUsrBGM9eqVdrMHx1Z7iC6bsAmIYESG6FAK0H5v1a7hX0jvLYSe5Dwpglm4vhc9OddgSi5MKBFjYxlvge5Y71tG9GQ9wI3ezapzllwF1p8A17mayOrLiPwJOYjBVioixm69rZ4UHbKjn+7mUAgL56msrqyQ/tgVonYdL4A5gAdkXGPPv1Xa7lJKkI+yyxjCu1Io+FuMUDEYqXQ9qMUodSYw+q+4aqbthGOGPPLu0AAWtOJd6YtK1lE9XD1kohao4NhwFzkCfH+E= ansible" 


- hosts: localhost
  become: true
  tasks:
    - name: Download Terraform binary
      get_url:
        url: https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
        dest: /tmp/terraform.zip
        mode: 0644

    - name: Unzip Terraform binary
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
        owner: root
        group: root


- hosts: web_servers
  become: true
  tasks: 

  - name: install apache & php packages
    tags: apache,ubuntu,apache2
    package: 
      name: 
         - httpd
         - php
      state: latest
      update_cache: yes

  - name: start httpd
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes

  - name: change e-mail address for admin
    tags: centos,apazhe,httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    register: httpd

  - name: restart httpd 
    tags: apache,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed 


  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
