- name: install apache & php packages
  tags: apache,ubuntu,apache2
  package:
      name:
         - httpd
         - php
      state: latest

- name: start httpd
  tags: apache,centos,httpd
  service:
      name: httpd
      state: started
      enabled: yes

- name: change e-mail address for admin
  tags: centos,apazhe,httpd
  lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
  register: httpd

- name: restart httpd
  tags: apache,httpd
  service:
      name: httpd
      state: restarted
  when: httpd.changed

- name: copy html file for site
  tags: apache,apache2,httpd
  copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
