- name: Download Terraform binary
  get_url:
    url: https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
    dest: /tmp/terraform.zip
    mode: 0644

- name: Unzip Terraform binary
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
